apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: MQ-DevOps-Demo
  owner: MQ-DevOps-Demo
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/MQ-DevOps-Demo/multi-tenancy-gitops-apps.git
